name: Update version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version'
        required: true
        default: patch
        type: choice
        options:
          - patch
          - minor
          - major
jobs:
  version:
    strategy:
      matrix:
        node-version: [16]
        os: [ubuntu-latest]

    name: Create new version ${{ github.event.inputs.version }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set git credentials
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Generate new version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push new version tag to repository
        run: git push origin main --tags
        
